### ISSUE TITLE
[CI/CD] Kubernetes - Persistent Volume Issue After Restart

### ISSUE THREAD

**Issue by JanDeRoeckDanone** [SAP/xsk#1019]
In some cases after deleting the XSK pod manually (to be reschedule by the Deployment), or by scaling down to zero and then scaling up, the XSK pod stalls into `Init:0/1` state.

Output from executing `kubectl describe pod xsk-xxx`:
**Events:**
|   Type      | Reason                      | Age  | From                               | Message |
| --------- | -------------------- | ---- | ----------------------- | --------- |
| Normal    | Scheduled                 | 35s | default-scheduler          | Successfully assigned default/xsk-... to ...eu.central-1.compute.internal |
| Warning  | FailedAttachVolume  | 36s | attachdetach-controller | Multi-Attach error for volume "pv-shoot--kyma--c-3721db5-..." Volume is already exclusively attached to one node and can't be attached to another |

**Comment by ThuF** [comment]
Could be related to the `accessModes` **ReadWriteOnce**:

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xsk-claim
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
```

More about the Access Modes could be found [here](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes):

> **ReadWriteOnce**
the volume can be mounted as read-write by a single node. ReadWriteOnce access mode still can allow multiple pods to access the volume when the pods are running on the same node.

The problem may occur when **Pod1** is scheduled on **Node1** and after restart/update **Pod1** is terminated and **Pod2** is scheduled on **Node2**.
