### ISSUE TITLE
[Research] Pipeline with Harbor on Kyma cluster

### ISSUE THREAD

**Issue by rdimitrov4** [SAP/xsk#1324]
1. Prepare the Harbor instance on Kyma cluster
2. Build a pipeline with Github Actions
3. Test the setup with XSK

**Comment by krasimirdermendzhiev** [comment]
At this moment Harbor has [issue](https://github.com/goharbor/harbor/issues/11906) with Istio, that's why Notary Server is not working.
 
Harbor internalTLS is not working with mTLS Istio, that's why is disabled internalTLS for Harbor.
 
Installation Harbor on Kyma 2
 
1. Enable istio injection for namespace
 
kubectl label namespace harbor-system istio-injection=enabled --overwrite
 
2. Add harbor helm repo
 
`helm repo add harbor https://helm.goharbor.io`
 
3. Get Api server
 
`kubectl config view | grep server`
 
*Note copy the server without "api" in the url.
 
4. Deploy harbor
 
```
helm upgrade --install harbor harbor/harbor -n harbor-system \
--set expose.type=clusterIP \
--set expose.tls.enabled=false \
--set externalURL='https://harbor/.<your-server-from-step-3>' \
--set nginx.replicas=0 \
--set notary.enabled=false \
--set chartmuseum.enabled=false
 ```
 
5. Create Istio Gateway for harbor
 
 ```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
name: harbor-gateway
namespace: harbor-system
spec:
selector:
istio: ingressgateway
servers:
- port:
number: 80
name: http-harbor
protocol: HTTP
hosts:
- harbor.<your-server-from-step-3>
tls:
httpsRedirect: true
- port:
number: 443
name: https-harbor
protocol: HTTPS
hosts:
- 'harbor.<your-api-server>'
tls:
mode: SIMPLE
credentialName: kyma-gateway-certs
 ```
 
6. Add Istio Virtual Service
 
 ```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
name: harbor
namespace: harbor-system
spec:
gateways:
- harbor-gateway
- mesh
hosts:
- harbor.<your-api-server>
http:
- name: 'registry'
match:
- port: 5000
route:
- destination:
host: harbor-registry.harbor-system.svc.cluster.local
port:
number: 5000
- name: 'core'
match:
- uri:
prefix: '/api/'
- uri:
prefix: '/service/'
- uri:
prefix: '/v2/'
- uri:
prefix: '/chartrepo/'
- uri:
prefix: '/c/'
route:
- destination:
host: harbor-core.harbor-system.svc.cluster.local
port:
number: 80
- name: 'portal'
route:
- destination:
host: harbor-portal.harbor-system.svc.cluster.local
port:
number: 80
 ```
 
7. Add Istio Service entry
 
 ```yaml
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
name: harbor-registry
namespace: harbor-system
spec:
hosts:
- harbor.<your-api-server>
- harbor-core
ports:
- number: 5000
name: http-registry
location: MESH_INTERNAL
resolution: NONE
 ```
 
Then you should be able to visit the Harbor portal at https://harbor.<your-api-server>
with username: `admin` and password: `Harbor12345`.
 
You can log in with docker cli `docker login harbor.<your-api-server>`
Tag some image `docker tag <some-image>:<tag> harbor.<your-api-server>/<project-name>/<repository>`
Push `docker push harbor.<your-api-server>/<project-name>/<repository>`

Introducing Cosign in Harbor v2.5.0
https://goharbor.io/blog/cosign-2.5.0/
