### ISSUE TITLE
[Helm] Add support for private images

### ISSUE THREAD

**Issue by ThuF** [SAP/xsk#1348]
As of now it's not possible to deploy private docker image via the XSK Helm Chart _(e.g. as part of a CI/CD pipeline, more details can be found at: https://www.xsk.io/lifecycle/cicd/)_, as there are no parameters about it:

```
helm upgrade --install xsk xsk/xsk \
          --set kyma.enabled=true \
          --set kyma.host=$KYMA_HOST \
          --set hana.enabled=true \
          --set hana.url='jdbc:sap://${{ secrets.HANA_URL }}/?encrypt=true&validateCertificate=false`' \
          --set hana.username=${{ secrets.HANA_USERNAME }} \
          --set hana.password='${{ secrets.HANA_PASSWORD }}' \
          --set persistentVolumeClaim.enabled=false \
          --set deployment.strategyType=RollingUpdate \
          --set application.image=${{secrets.DOCKER_REGISTRY}}/${{ github.event.inputs.applicationRepository }}:${{ github.event.inputs.applicationReleaseVersion }}
```

I suggest that we should add support for the following parameters:
- `application.dockerServer` or `application..privateDockerRegistryServer`
- `application.dockerUsername` or `application..privateDockerRegistryUsername`
- `application.dockerPassword` or `application..privateDockerRegistryPassword`
- `application.dockerEmail` or `application..privateDockerRegistryEmail`

As a result docker registry secret should be created and **imagePullSecrets** should be set in the deployment:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: myregistrykey
  namespace: awesomeapps
data:
  .dockerconfigjson: UmVhbGx5IHJlYWxseSByZWVlZWVlZWVlZWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWxsbGxsbGxsbGxsbGxsbGxsbGxsbGxsbGxsbGxsbGx5eXl5eXl5eXl5eXl5eXl5eXl5eSBsbGxsbGxsbGxsbGxsbG9vb29vb29vb29vb29vb29vb29vb29vb29vb25ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubmdnZ2dnZ2dnZ2dnZ2dnZ2dnZ2cgYXV0aCBrZXlzCg==
type: kubernetes.io/dockerconfigjson
```

Reference implementation details could be found here:
- https://github.com/SAP/xsk/blob/b811dcac33c18d8059eb2f99fe937fd10362d087/releng/helm-charts/xsk-kpack/templates/kpack.yaml#L9-L16
- https://github.com/SAP/xsk/blob/b811dcac33c18d8059eb2f99fe937fd10362d087/releng/helm-charts/xsk-kpack/templates/_helpers.tpl#L1-L5
- https://github.com/SAP/xsk/blob/b811dcac33c18d8059eb2f99fe937fd10362d087/releng/helm-charts/xsk-kpack/values.yaml#L18-L28
