### ISSUE TITLE
Add option in ci/cd for publish application image in Github package.

### ISSUE THREAD

**Issue by krasimirdermendzhiev** [SAP/xsk#1752]
We need option to publish the application image to Github repository package.

**Comment by krasimirdermendzhiev** [comment]
https://github.com/SAP/xsk/commit/75568b4242e1ce0fcd6268d0eec519061bfab02e

![Screenshot 2022-06-30 at 14 09 47](https://user-images.githubusercontent.com/82384876/176663158-022a9c37-cc7a-441c-98e7-7e03b14d52d3.png)

**Comment by krasimirdermendzhiev** [comment]
The option can be set with environment variable

```yaml
jobs:
   build:
       runs-on: ubuntu-latest
       env:
           publishPackageInRepository: true
```
