### ISSUE TITLE
[CI/CD] Add support for Buildpacks

### ISSUE THREAD

**Issue by ThuF** [SAP/xsk#182]
Add support for `Buildpacks`:
- [Kpack](https://github.com/pivotal/kpack)
- [Buildpacks](https://buildpacks.io/)
- [Buildpack - Stack](https://buildpacks.io/docs/operator-guide/create-a-stack/)

Outcome:
- [XSK Buildpack](https://github.com/SAP/xsk/tree/main/releng/buildpacks/xsk)
- Generic Java Buildpack

**Comment by ThuF** [comment]
DockerHub XSK Buildpack related repositories:
- [dirigiblelabs/kneo-xsk-buildpack](https://hub.docker.com/r/dirigiblelabs/kneo-xsk-buildpack/tags)
- [dirigiblelabs/kneo-xsk-stack-base](https://hub.docker.com/r/dirigiblelabs/kneo-xsk-stack-base/tags)
- [dirigiblelabs/kneo-xsk-stack-build](https://hub.docker.com/r/dirigiblelabs/kneo-xsk-stack-build/tags)
- [dirigiblelabs/kneo-xsk-stack-run](https://hub.docker.com/r/dirigiblelabs/kneo-xsk-stack-run/tags)

**Comment by ThuF** [comment]
## Prerequisites

- Install Kpack on your Kubernetes/Kyma cluster
- Create `ClusterStore`, `ClusterStack` and `Builder`:

```yaml
apiVersion: kpack.io/v1alpha1
kind: ClusterStore
metadata:
  name: kneo-xsk-store
spec:
  sources:
  - image: dirigiblelabs/kneo-xsk-buildpack
---
apiVersion: kpack.io/v1alpha1
kind: ClusterStack
metadata:
  name: kneo-xsk-stack
spec:
  id: "com.sap.kneo.xsk"
  buildImage:
    image: "dirigiblelabs/kneo-xsk-stack-build"
  runImage:
    image: "dirigiblelabs/kneo-xsk-stack-run"
---
apiVersion: kpack.io/v1alpha1
kind: Builder
metadata:
  name: kneo-xsk
spec:
  serviceAccount: <your-service-account>
  tag: <your-docker-organization>/<your-docker-builder-repository>
  stack:
    name: kneo-xsk-stack
    kind: ClusterStack
  store:
    name: kneo-xsk-store
    kind: ClusterStore
  order:
  - group:
    - id: dirigiblelabs/kneo-xsk-buildpack
```

> _**Note**: Replace `<your-service-account>` with your ServiceAccount (sample could be found [here](https://github.com/SAP/xsk/blob/main/releng/buildpacks/xsk/kpack/service-account.yaml))._

> _**Note**: Also replace `<your-docker-organization>/<your-docker-builder-repository>` with your Docker Repository, where the Docker Image Builder will be hosted (e.g. `my-organization/my-builder`)_

## Usage

```yaml
apiVersion: kpack.io/v1alpha1
kind: Image
metadata:
  name: xsk-application
  namespace: default
spec:
  tag: <your-docker-organization>/<your-application-docker-image-repository>
  serviceAccount: <your-service-account>
  builder:
    name: kneo-xsk
    kind: Builder
  source:
    blob:
      url: https://github.com/SAP/xsk/raw/main/samples/products.zip
```

> _**Note**: Replace `<your-service-account>` with your ServiceAccount (sample could be found [here](https://github.com/SAP/xsk/blob/main/releng/buildpacks/xsk/kpack/service-account.yaml))._

> _**Note**: Also replace `<your-docker-organization>/<your-application-docker-image-repository>` with your Docker Repository, where the Docker Image Builder will be hosted (e.g. `my-organization/my-application`)_
