### ISSUE TITLE
[CI/CD] Deploy every new release on public cluster

### ISSUE THREAD

**Issue by krasimirdermendzhiev** [SAP/xsk#355]
Deploy every new release on public cluster.

**Comment by ThuF** [comment]
Separate HANA Cloud instance to be created and bound to the "public" XSK instance. For logging purposes GitHub logging to be used via Keycloak

**Comment by ThuF** [comment]
XSK Trial URL: https://xsk-trial.kneo.promart.shoot.canary.k8s-hana.ondemand.com
Login via `SAP Identity and Access Management Tenant`: https://cee.accounts400.ondemand.com/admin/

`Deployment.yaml`
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xsk-trial
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xsk-trial
  template:
    metadata:
      labels:
        app: xsk-trial
    spec:
      containers:
      - name: xsk-trial
        image: dirigiblelabs/xsk-kyma:latest
        imagePullPolicy: Always
        env:
        - name: DIRIGIBLE_THEME_DEFAULT
          value: fiori
        - name: DIRIGIBLE_HOST
          value: https://xsk-trial.kneo.promart.shoot.canary.k8s-hana.ondemand.com
        - name: url
          value: ...
        - name: clientid
          value: ...
        - name: clientsecret
          value: ...
        - name: verificationkey
          value: ...
        - name: xsappname
          value: ...
        - name: DIRIGIBLE_DATABASE_PROVIDER
          value: custom
        - name: DIRIGIBLE_DATABASE_CUSTOM_DATASOURCES
          value: HANA
        - name: DIRIGIBLE_DATABASE_DATASOURCE_NAME_DEFAULT
          value: HANA
        - name: HANA_URL
          value: ...
        - name: HANA_DRIVER
          value: com.sap.db.jdbc.Driver
        - name: HANA_USERNAME
          value: ...
        - name: HANA_PASSWORD
          value: ...
        volumeMounts:
        - name: xsk-trial-volume
          mountPath: /usr/local/tomcat/target/dirigible
        ports:
        - containerPort: 8080
          name: xsk-trial
          protocol: TCP
      volumes:
      - name: xsk-trial-volume
        persistentVolumeClaim:
          claimName: xsk-trial-claim
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: xsk-trial
  name: xsk-trial
  namespace: default
spec:
  ports:
  - name: xsk-trial
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: xsk-trial
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xsk-trial-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: xsk-trial
  namespace: default
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
  - accessStrategies:
    - config: {}
      handler: noop
    methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - HEAD
    path: /.*
  service:
    host: xsk-trial.kneo.promart.shoot.canary.k8s-hana.ondemand.com
    name: xsk-trial
    port: 8080
```

`xs-security.json`

```json
{
   "xsappname": "xsk-trial-xsuaa",
   "oauth2-configuration": {
      "token-validity": 7200,
      "redirect-uris": [
         "xsk-trial.kneo.promart.shoot.canary.k8s-hana.ondemand.com"
      ]
   },
   "scopes": [
      {
         "name": "$XSAPPNAME.Developer",
         "description": "Developer scope"
      },
      {
         "name": "$XSAPPNAME.Operator",
         "description": "Operator scope"
      }
   ],
   "role-templates": [
      {
         "name": "Developer",
         "description": "Developer related roles",
         "scope-references": [
            "$XSAPPNAME.Developer"
         ]
      },
      {
         "name": "Operator",
         "description": "Operator related roles",
         "scope-references": [
            "$XSAPPNAME.Operator"
         ]
      }
   ],
   "role-collections": [
      {
         "name": "XSK Developer",
         "description": "XSK Developer",
         "role-template-references": [ 
            "$XSAPPNAME.Developer"
         ]
      },
      {
         "name": "XSK Operator",
         "description": "XSK Operator",
         "role-template-references": [ 
            "$XSAPPNAME.Operator"
         ]
      }
   ]    
}
```

More details about the setup could be found [here](https://www.dirigible.io/help/setup/kyma/).
