### ISSUE TITLE
[Research] Istio & Calico - network policy configuration

### ISSUE THREAD

**Issue by ThuF** [SAP/xsk#454]
Research what are the current capabilities and what should be the optimal network policy configurations of Istio & Calico in order to guarantee isolated cluster environment for multiple customer applications - **Kubernetes Virtual Cluster**.

Related to: https://github.com/SAP/xsk/issues/150

**Comment by rdimitrov4** [comment]
**Kubernetes Multitenancy Architecture Model**

1. **Assign Each Tenant A Separate Namespace**

-  Create two namespaces
` $ kubectl create ns namespace1`
`$ kubectl create ns namespace2`

- Label the namespaces
`$ kubectl label ns namespace1 name=namespace1`
`$ kubectl label ns namespace2 name=namespace2`

2. **Use Calico Network Policy to Isolate Traffic between namespaces**

- To isolate the namespaces at network level, we have to apply network policy on both namespaces

```
apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: deny-namespaces
spec:
  types:
  - Ingress
  - Egress
  ingress:
  - action: Allow
    protocol: TCP
    source:
      namespaceSelector: name == 'namespace1'
  - action: Allow
    protocol: TCP
    source:
      namespaceSelector: name == 'kube-system'
  - action: Allow
    protocol: TCP
    source:
      namespaceSelector: name == 'kube-public'
  - action: Allow
    protocol: TCP
    source:
      namespaceSelector: name == 'kube-node-lease'
  - action: Allow
    protocol: TCP
    source:
      namespaceSelector: name == 'istio-system'
  - action: Allow
    protocol: TCP
    source:
      namespaceSelector: name == 'kyma-installer'
  - action: Allow
    protocol: TCP
    source:
      namespaceSelector: name == 'kyma-integration'
  - action: Allow
    protocol: TCP
    source:
      namespaceSelector: name == 'kyma-system'
  - action: Allow
    protocol: TCP
    source:
      namespaceSelector: name == 'kyma-system-space'
  egress:
  - action: Allow
```

- This policy will block the access from namespace2, allowing Ingress traffic from namespace1 itself and the necessary Kubernetes,Kyma and Istio system namespaces

- Create a file named namespace1-policy.yaml containing the code above.
`$nano namespace1-policy.yam`

- Apply the policy on namespace1
`$ kubectl create -f namespace1-policy.yaml -n=namespace1`

Similar NetworkPolicy is created and applied for namespace2
```
apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: deny-namespaces
spec:
  types:
  - Ingress
  - Egress
  ingress:
  - action: Allow
    protocol: TCP
    source:
      namespaceSelector: name == 'namespace2'
  - action: Allow
    protocol: TCP
    source:
      namespaceSelector: name == 'kube-system'
  - action: Allow
    protocol: TCP
    source:
      namespaceSelector: name == 'kube-public'
  - action: Allow
    protocol: TCP
    source:
      namespaceSelector: name == 'kube-node-lease'
  - action: Allow
    protocol: TCP
    source:
      namespaceSelector: name == 'istio-system'
  - action: Allow
    protocol: TCP
    source:
      namespaceSelector: name == 'kyma-installer'
  - action: Allow
    protocol: TCP
    source:
      namespaceSelector: name == 'kyma-integration'
  - action: Allow
    protocol: TCP
    source:
      namespaceSelector: name == 'kyma-system'
  - action: Allow
    protocol: TCP
    source:
      namespaceSelector: name == 'kyma-system-space'
  egress:
  - action: Allow
```
This method limits the traffic between the tenant namespaces

3. **Leverage RBAC to enforce control**

Kubernetes uses Role-based Access Control (RBAC) to enable users to control access to resources.

- User service accounts and roles with role bindings, with the necessary access to Kyma system resources and Kubernetes system resources are created for certain access to the namespace resources.

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: user1-service-account
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: user1-role
rules:
  - apiGroups:
      - ""
      - extensions
      - batch
      - apps
      - gateway.kyma-project.io
      - servicecatalog.k8s.io
      - servicecatalog.kyma-project.io
    resources:
      - deployments
      - replicasets
      - pods
      - pods/exec
      - jobs
      - configmaps
      - apirules
      - serviceinstances
      - servicebindings
      - services
      - secrets
      - servicebindingusages
    verbs:
      - create
      - update
      - patch
      - delete
      - get
      - list
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: user1-role-binding
subjects:
  - kind: ServiceAccount
    name: user1-service-account
roleRef:
  kind: Role
  name: user1-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user1-config-map
data:
  out: "Congrats, you created the user role successfully!"
```
- Under the apiGroups: section in rules: , the Kyma gateway (Istio Ingress Gateway) and k8s and kyma-project service catalogs are a must

- Create a file named user1-sa.yaml containing the code above.
`$nano user1-sa.yaml`

- Apply the file on namespace1
`$ kubectl create -f user1-sa.yaml-n=namespace1`

This is repeated for namespace2 with different ServiceAccount and Role names

4. Enforcing Resource Quotas for the namespaces is optional but recommended

-  Related to #493 

---
Tested on Gardener Kyma cluster with XSK deployments for each namespace.

**Comment by krasimirdermendzhiev** [comment]
Can you provide some test steps?

**Comment by rdimitrov4** [comment]
For the RBAC testing we need kubeconfig yaml files for the respective Service Accounts (user1-service-account and user2-service-account)

To generate the kubeconfig files we can create a script for each user
```
user2.sh

# API server URL is api.KYMA_CLUSTER_DOMAIN
API_SERVER_URL=$(kubectl config current-context)

# the name of the secret containing the service account token goes here
SECRET_NAME=$(kubectl get sa -n namespace2 user2-service-account -ojsonpath='{.secrets[0].name}')

CA=$(kubectl get secret/${SECRET_NAME} -n namespace2 -o jsonpath='{.data.ca\.crt}')
TOKEN=$(kubectl get secret/${SECRET_NAME} -n namespace2 -o jsonpath='{.data.token}' | base64 --decode)

echo "
apiVersion: v1
kind: Config
clusters:
- name: default-cluster
  cluster:
    certificate-authority-data: ${CA}
    server: https://api.${API_SERVER_URL}
users:
- name: default-user
  user:
    token: ${TOKEN}
contexts:
- name: default-context
  context:
    cluster: default-cluster
    namespace: default
    user: default-user
current-context: default-context
"
```
After that we give permissions to execute the file and run the script with output to a yaml file
```
chmod +x user2.sh
./user2.sh > kubeconfig-user2.yaml
```

After exporting the kubeconfig file we operate as user2
`export KUBECONFIG=$KUBECONFIG:/<your-user>/<your-work-directory>/kubeconfig-user2.yaml`

As user2 we can operate with the given apiGroups and resources that are in the Role's configuration in the namespace where we applied them (in this case namespace2)
```
$ kubectl get pods -n namespace2
NAME                     READY   STATUS    RESTARTS  
nginx-6799fc88d8-sj4cd   2/2     Running   0         
xsk-6998b755b7-kfjgw     2/2     Running   0    
     
$ kubectl get pods -n namespace1
Error from server (Forbidden): pods is forbidden: User "system:serviceaccount:namespace2:user2-service-account" cannot list resource "pods" in API group "" in the namespace "namespace1"

$ kubectl get pods 
Error from server (Forbidden): pods is forbidden: User "system:serviceaccount:namespace2:user2-service-account" cannot list resource "pods" in API group "" in the namespace "default"

$ kubectl create -f ubuntu.yaml 
Error from server (Forbidden): error when creating "ubuntu.yaml": pods is forbidden: User "system:serviceaccount:namespace2:user2-service-account" cannot create resource "pods" in API group "" in the namespace "default"

$ kubectl create -f ubuntu.yaml -n namespace1
Error from server (Forbidden): error when creating "ubuntu.yaml": pods is forbidden: User "system:serviceaccount:namespace2:user2-service-account" cannot create resource "pods" in API group "" in the namespace "namespace1"

$ kubectl create -f ubuntu.yaml -n namespace2
pod/ubuntu created
```
