### ISSUE TITLE
[Research] Deployment Resource Limits

### ISSUE THREAD

**Issue by ThuF** [SAP/xsk#493]
Determine what are the resource limits per XSK deployment:
- https://kubernetes.io/docs/concepts/policy/resource-quotas/
- https://kubernetes.io/docs/concepts/policy/limit-range/
- https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/memory-constraint-namespace/

**Comment by krasimirdermendzhiev** [comment]
- ### First phase - Deploy

When we deploying XSK we can see that we need almost 800m cpu and around 600-700Mi.
```yaml
k top pod xsk-f6fc995f9-2cjdx --use-protocol-buffers
NAME                  CPU(cores)   MEMORY(bytes)   
xsk-f6fc995f9-2cjdx   792m         626Mi  
```
That's why we can take this and configure resources limit with:

Resource limits:
```yaml
limits:
  cpu: 800m
  memory: 900Mi
```
- ### Second Phase - Running

When XSK is deployed we can see that CPU is under 100m and MEMORY is under 900Mi.
```
k top pod xsk-f6fc995f9-vhd6j --use-protocol-buffers
NAME                  CPU(cores)   MEMORY(bytes)   
xsk-f6fc995f9-vhd6j   44m          779Mi 
```

That's why we can configure requests with: 
 ```yaml
limits:
  cpu: 800m
  memory: 900Mi
requests:
  cpu: 200m
  memory: 700Mi
```
This resource limits are the same for local deploy and Kyma. This is the minimal limits and when you deploy your application you need to consider what resources need for your application.

- ### Limit range
We can configure limit range, but first check what values you have for node resources. If you have values for node resources like this:
| Resource   | Requests                  | Limits                       |
| -----------| -------------------- |--------------------|
| cpu            | 819m (42%)              |3232m (168%)         |
| memory     | 884096562 (12%)   |6564049328 (95%)|

You can configure limit range, which will work with XSK. 
```yaml
apiVersion: v1
kind: LimitRange
metadata:
 name: limit-max-min
spec:
 limits:
 - max:
     cpu: 900m 
     memory: 1Gi     
   min:
     cpu: 200m
     memory: 700Mi     
   type: Container
```
After we configure rate limit we can't set cpu more than 900m and memory 1Gi. If we not using limits we will take default values.
| Resource   | Min      | Max         | Default Request |
| -----------| -------|----------|-----------------|
| cpu            | 200m.  | 900m      | 900m                 |
| memory     | 700Mi | 1Gi.          | 1Gi                      |

For limit range in Kyma we need to check again the node resources before configure limit range. At this example we can see that can't add this range because insufficient cpu.

| Resource   | Requests                    | Limits                                     |
| -----------| ---------------------|----------------------------|
| cpu            | 3228m (82%)            | 13798m (351%)                     |
| memory     | 4246338032 (28%) | 19465681348800m (128%) |

- ### Constraints for a Namespace
We can use the previous limit range for every different namespace.

- ### Resource quota prevent to create more pods
```yaml
apiVersion: v1
kind: ResourceQuota
metadata:
 name: pod-examples
spec:
 hard:
   pods: "2"
```
And if we try to deploy with value 3 for replicaCount
```
helm install xsk xsk --set replicaCount=3 
```    
we will see 2 pods deployed
```
xsk-f6fc995f9-xrp75   1/1     Running   0          77s
xsk-f6fc995f9-v62g7   1/1     Running   0          80s
```
