### ISSUE TITLE
[Research] Trial Custom Domain

### ISSUE THREAD

**Issue by ThuF** [SAP/xsk#495]
Research how to configure the `*.xsk.io` domain on Gardener.

**Comment by krasimirdermendzhiev** [comment]
1.  Create subdomain for *.xsk.io
2. Create AWS hosted zone for the subdomain
https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/CreatingNewSubdomain.html
3. Add AWS Route 53 DNS Provider
https://github.com/gardener/external-dns-management/blob/master/docs/aws-route53/README.md
4. Create a DNSEntry
https://github.com/gardener/external-dns-management
5. Prepare Gardener extension - `shoot-dns-service` and `shoot-cert-service`
https://gardener.cloud/docs/tutorials/shoot_istio_dns_certs/
```
extensions:
    - type: shoot-cert-service
      providerConfig:
        apiVersion: service.cert.extensions.gardener.cloud/v1alpha1
        issuers:
          - email: me@mail.com
            name: mydomain
            server: 'https://acme-v02.api.letsencrypt.org/directory'
          - email: me@mail.com
            name: mydomain-staging
            server: 'https://acme-staging-v02.api.letsencrypt.org/directory'
```
6. Configure Istio Ingress Gateway

```
annotations:
    cert.gardener.cloud/issuer: mydomain-staging
    cert.gardener.cloud/secretname: wildcard-tls
    dns.gardener.cloud/class: garden
    dns.gardener.cloud/dnsnames: "*.gsicdc.mydomain.io"
    dns.gardener.cloud/ttl: "120"
```

7.  Create Istio Gateway and VirtualService

```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: httpbin-gw
  namespace: production
spec:
  selector:
    istio: ingressgateway #! use istio default ingress gateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    tls:
      httpsRedirect: true
    hosts:
    - "httpbin.gsicdc.mydomain.io"
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: wildcard-tls
    hosts:
    - "httpbin.gsicdc.mydomain.io"
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: httpbin-vs
  namespace: production
spec:
  hosts:
  - "httpbin.gsicdc.mydomain.io"
  gateways:
  - httpbin-gw
  http:
  - match:
    - uri:
        regex: /.*
    route:
    - destination:
        port:
          number: 8000
        host: httpbin

```
