### ISSUE TITLE
[Research] Test xsk with containerd

### ISSUE THREAD

**Issue by krasimirdermendzhiev** [SAP/xsk#551]
Test xsk container runtime with containerd instead of docker.

With Kubernetes v1.20 the built-in dockershim was deprecated and is scheduled to be removed with v1.24 .

**Comment by krasimirdermendzhiev** [comment]
XSK is tested on Gardener with gVisor and containerd
```
workers:
      - cri:
          name: containerd
          containerRuntimes:
            - type: gvisor
```

Test with sample https://github.com/SAP/xsk/tree/main/samples/xsjs-simple
