### ISSUE TITLE
Migration path for roles from xsprivileges and xsaccess

### ISSUE THREAD

**Issue by dpanayotov** [SAP/xsk#735]
Process all roles from xsprivileges and move them to a security descriptor
How to handle different authentication types from xsaccess

**Comment by dpanayotov** [comment]
## Option 1 - Use XSUAA APIs
Reference - https://api.sap.com/api/AuthorizationAPI/resource
### Limitations
1. apiaccess plan is available only through Cloud Foundry
2. There is no API to create new role templates - one must be predefined in the xs-security.json

### Flow
1. Get credentials for apiaccess plan (through CF)
2. In the xs-security.json for XSK add a fake role-template and fake scope like so
```yml
....
    role-collections:
    - description: XSK Developer
      name: XSK Developer
      role-template-references:
      - $XSAPPNAME.Developer
    - description: XSK Operator
      name: XSK Operator
      role-template-references:
      - $XSAPPNAME.Operator
    role-templates:
    - description: Developer related roles
      name: Developer
      scope-references:
      - $XSAPPNAME.Developer
    - description: Operator related roles
      name: Operator
      scope-references:
      - $XSAPPNAME.Operator
      ----
    - description: XS Privileges scope
      name: XSPrivileges
      ----
      scope-references:
      - "$XSAPPNAME.xsprivileges"
    scopes:
    - description: Developer scope
      name: $XSAPPNAME.Developer
    - description: Operator scope
      name: $XSAPPNAME.Operator
      ----
    - description: XSPrivileges scope
      name: "$XSAPPNAME.xsprivileges"
      ----
....
```
3. Obtain a token using the credentials from apiaccess instance
4. Create a new role from the template
```
POST https://api.authentication.eu10.hana.ondemand.com/sap/rest/authorization/v2/apps/roles
{
  "appDescription": "This is an example description of an application.",
  "appName": "xsk-xsuaa!t114536",
  "description": "This is the xsprivilege role.",
  "isReadOnly": false,
  "name": "XSPrivilegeRole",
  "roleTemplateAppId": "xsk-xsuaa!t114536",
  "roleTemplateName": "XSPrivileges",
  "scopes": [
    {
      "description": "Display values",
      "name": "xsk-xsuaa!t114536.Privilege"
    }
  ]
}
```
5. Create role collection for roles
```
POST https://api.authentication.eu10.hana.ondemand.com/sap/rest/authorization/v2/rolecollections
{
  "name": "RCFromXSPrivilege",
  "description": "Enables users to view the items.",
  "roleReferences": [
    {
      "roleTemplateAppId": "xsk-xsuaa!t114536",
      "roleTemplateName": "XSPrivileges",
      "name": "XSPrivileges"
    }
  ],
  "isReadOnly": false
}
```

## Option 2 - update the k8s service instance
Use the k8s java client to patch a CR - https://github.com/kubernetes-client/java/blob/master/examples/examples-release-12/src/main/java/io/kubernetes/client/examples/PatchExample.java#L66
### Limitations
**Both limitations from above are not relevant here**
1. Usable only in Kyma as it depends on ServiceInstance resource

### Flow
1. Find the correct service instance bound to XSK
2. Change the spec to include the new scope, role-template and role collections
3. Apply the resource - this will be picked up by the service catalog and sent to XSUAA for processing
