### ISSUE TITLE
Logout and login does not refresh scopes

### ISSUE THREAD

**Issue by dpanayotov** [SAP/xsk#820]
**Describe the bug**
If I assign myself roles they are not reflected in the token after re-login

> What version of the XSK are you using?
[latest](https://github.com/SAP/xsk/commit/68b14fade62dcde009aa974ca61ae0e723250689) 

**To Reproduce**
1. Run XSK on Kyma using XSUAA
2. Login and see the scopes in the token
3. Update XSUAA instance to create new role (`kubectl apply -f xsuaa.yml`)
4. Assign new role collection from BTP Cockpit
5. Logout from XSK
6. Login again
7. See the scopes in the token
8. See that the new scope is not reflected

**Expected behavior**
The new scope is in the token

**Additional context**
This is not always reproduced. Sometimes after re-login the scopes are there, sometimes they are not

Here's a sample of the spec from the xsuaa service instance
```yml
spec:
  parameters:
    oauth2-configuration:
      redirect-uris:
      - <replace-with-yours>
      token-validity: 7200
    role-collections:
    - description: XSK Developer
      name: XSK Developer
      role-template-references:
      - $XSAPPNAME.Developer
    - description: XSK Operator
      name: XSK Operator
      role-template-references:
      - $XSAPPNAME.Operator
    - description: XSK Admin
      name: XSK Admin
      role-template-references:
      - $XSAPPNAME.Admin
    role-templates:
    - description: Developer related roles
      name: Developer
      scope-references:
      - $XSAPPNAME.Developer
    - description: Operator related roles
      name: Operator
      scope-references:
      - $XSAPPNAME.Operator
    - description: Admin related roles
      name: Admin
      scope-references:
      - "$XSAPPNAME.Admin"
    scopes:
    - description: Developer scope
      name: $XSAPPNAME.Developer
    - description: Operator scope
      name: $XSAPPNAME.Operator
    - description: Admin scope
      name: "$XSAPPNAME.Admin"
    xsappname: xsk-xsuaa
```
